#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from typing import Any

from .logger import Logger
from .oracle_connection_manager import OracleConnectionManager
from .oracle_driver import get_cx_oracle


class OracleSessionPool:
    def __init__(
        self,
        cfg: dict[str, Any],
        logger: Logger,
        connection_manager: OracleConnectionManager | None = None,
    ) -> None:
        self._cfg = cfg or {}
        self._logger = logger
        self.enabled = bool(self._cfg.get("enabled", False))
        self._connection_manager = connection_manager or OracleConnectionManager(logger)
        self._owns_connection_manager = connection_manager is None

    def fetch_many(
        self,
        *,
        sql: str,
        params: dict[str, Any] | None = None,
        limit: int = 1000,
    ) -> list[dict[str, Any]]:
        if not self.enabled:
            return []

        normalized_sql = str(sql).strip()
        if not normalized_sql:
            return []

        rows = self._connection_manager.fetch_many_from_pool(
            self._cfg,
            sql=normalized_sql,
            params=params or {},
            limit=max(1, int(limit)),
        )
        return rows

    def close(self) -> None:
        if self._owns_connection_manager:
            self._connection_manager.close_all()


class OracleResultWriter:
    def __init__(
        self,
        cfg: dict[str, Any],
        logger: Logger,
        connection_manager: OracleConnectionManager | None = None,
    ) -> None:
        self._logger = logger
        self.enabled = bool(cfg.get("enabled", False))
        self._dry_run = bool(cfg.get("dry_run", True))
        self._dsn = str(cfg.get("_dsn") or cfg.get("dsn", "")).strip()
        self._table = self._normalize_table_name(str(cfg.get("table", "PIPELINE_RESULTS")))
        self._ensure_table_enabled = bool(cfg.get("ensure_table", True))
        self._connection_manager = connection_manager or OracleConnectionManager(logger)
        self._owns_connection_manager = connection_manager is None

    def _normalize_table_name(self, table_name: str) -> str:
        normalized = str(table_name).strip().upper()
        if not re.fullmatch(r"[A-Z][A-Z0-9_]{0,127}", normalized):
            raise ValueError(f"Invalid Oracle table name: {table_name}")
        return normalized

    def _get_conn(self):
        return self._connection_manager.get_connection(self._dsn, threaded=True)

    def _ensure_table(self) -> None:
        cx_oracle = get_cx_oracle()

        conn = self._get_conn()
        cursor = conn.cursor()
        try:
            cursor.execute(
                f"""
                CREATE TABLE {self._table} (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    obj_id VARCHAR2(128),
                    node_id VARCHAR2(128),
                    status VARCHAR2(16),
                    score NUMBER,
                    digest VARCHAR2(128),
                    payload_json CLOB,
                    created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP
                )
                """
            )
            conn.commit()
        except cx_oracle.DatabaseError as exc:
            error_obj = exc.args[0] if exc.args else None
            if getattr(error_obj, "code", None) != 955:
                raise
        finally:
            cursor.close()

    def write_many(self, results: list[dict[str, Any]]) -> int:
        if not self.enabled:
            return 0
        if self._dry_run:
            self._logger.info("[Processing] oracle_write dry-run count=%d", len(results))
            return len(results)
        if not self._dsn:
            self._logger.warning("[Processing] oracle_write enabled but dsn missing")
            return 0
        if not results:
            return 0

        if self._ensure_table_enabled:
            self._ensure_table()

        conn = self._get_conn()
        cursor = conn.cursor()
        try:
            rows = [
                (
                    str(item.get("obj_id", "")),
                    str(item.get("node_id", "")),
                    str(item.get("result_status", "")),
                    int(item.get("result_score", 0)),
                    str(item.get("result_digest", "")),
                    json.dumps(item, ensure_ascii=False, default=str),
                )
                for item in results
            ]
            cursor.executemany(
                f"""
                INSERT INTO {self._table} (
                    obj_id,
                    node_id,
                    status,
                    score,
                    digest,
                    payload_json
                ) VALUES (
                    :1,
                    :2,
                    :3,
                    :4,
                    :5,
                    :6
                )
                """,
                rows,
            )
            conn.commit()
            return len(rows)
        finally:
            cursor.close()

    def close(self) -> None:
        if self._owns_connection_manager:
            self._connection_manager.close_all()
